### ISSUE TITLE
Is it possible to add custom obstacles 

### ISSUE THREAD

**Issue by ajay1606** [ntnu-arl/lidar_simulator#1]
Hello,

It's a very much useful tool, thanks for your efforts in developing it. It would be very nice to see the tool working, withh adding option to include custom object.

Regards,
Ajay

**Comment by mihirk284** [comment]
Hi Ajay,

This repository is meant to provide an interface to simulate lidar sensors in Gazebo Classic. The models spawned in a Gazebo environment are independent of the functionalities of this package.

We provide an example launch file within this package where the lidar is simulated in an empty world. Perhaps changing the world file to another world file containing the obstacles of your choice would help.

If you feel that I have not understood your question correctly, could you please elaborate your question?

Thanks,
Mihir Kulkarni

**Comment by mihirk284** [comment]
Closing this as issue is related to use case for other repositories.
